### PR TITLE
Implemented Import/Export XML

### PR DESCRIPTION
**Pull request by sea5kg**

### CODE REVIEW

**Comment by mrooney** [comment]
Hey there, thanks for your contribution and apologies for the delay! I'm currently not actively maintaining this project, but I'm very open to a new maintainer. Are you interested in being a maintainer of this repo and handling any PRs that come in?

**Comment by sea5kg** [comment]
Hello. I wish try.

**Review by mrooney — APPROVED** [review]
Looks great, thanks!

**Comment by mrooney** [comment]
Thanks so much! I've added you as a contributor to this repository, and you should receive an invitation. For your first action as a maintainer why don't you try merging your new PR :D

**Comment by sea5kg** [comment]
> Thanks so much! I've added you as a contributor to this repository, and you should receive an invitation. For your first action as a maintainer why don't you try merging your new PR :D

You welcome )

Yes, I receive and accept invitation, thanks you )

About PR - I will try today later ))

**Pull request merged**
