### PR TITLE
fix wxwidgets 3.0 compatibility

### PR DESCRIPTION
**Pull request by xuzhen**

### CODE REVIEW

**Comment by jtlpa** [comment]
issues found (with these patches) running python-wxgtk3.x on Debian 8
    - disappearing rows when editing last of many transaction (white-on-white text)
      need at least 2-3 pages of transactions 
    - hint text always stays light gray 
    - can not [Tab] or [Enter] out of date field when entering a new transaction
    - startup Gtk-CRITICAL error message

**Comment by xuzhen** [comment]
the gray text bug: http://trac.wxwidgets.org/ticket/16583

**Comment by mrooney** [comment]
Thank you so much for digging in to these, this is really awesome! Merged and I can see if I can make it simpler to install an updated version on Debian/Ubuntu.

**Comment by mrooney** [comment]
And, please do send along any PRs for future improvements you make :D

**Pull request merged**
